<form enctype="multipart/form-data" action="default/theme/save" method="post">
    <dl class="zend_form">
        <?php echo $this->form->style?>
        
        <br />
        
        <?php echo $this->form->logo?>
        <img src="upload/<?php echo $this->logo?>" /><br />
        
        <br />

        <?php echo $this->form->custom_css?>
        <?php echo $this->form->Save?>
    </dl>
</form>