<div class="right">
    <?php echo $this->ajax('back', 'content/restriction/index', 2) ?>
</div>
<div class="restriction-time">
    <?php echo $this->form ?>
</div>
<script type="text/javascript">
    $('.date').datepicker().mask('99/99/9999');
    
    $(".restriction-time form").submit(function() {
        var $this = $(this);
		$.post(this.action, $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    
    $('input[type=button], input[type=submit]').button();
</script>