<?php foreach($this->data as $data):?>
    <?php $name = $data->getBasename();?>
    <?php if (!$data->isDot() && ! $data->isFile()) :?>
    <div class="padding dotted span5 margin ohidden" style="height: 57px;">
            <?php $filename = $data->getPathname(). '/configuration.xml';?>
            <?php if (file_exists($filename)):?>
                <?php 
                    $config = simplexml_load_file($filename);
                    $name = strtolower((string) $config->name);
                ?>
                <strong><?php echo $this->translate((string) $config->name)?></strong> |
                <?php if (in_array($name, $this->activated)) :?>
                    <a href="admin/plugin/desactivate/name/<?php echo $name?>">
                        <?php echo $this->translate('desactivate')?></a>
                <?php else:?>
                    <a href="admin/plugin/activate/name/<?php echo $name?>"><?php echo $this->translate('activate')?></a>
                    <?php if (in_array($name, $this->installed)) :?>
                        - <a href="admin/plugin/uninstall/name/<?php echo $name?>"><?php echo $this->translate('uninstall')?></a>
                    <?php endif;?>
                <?php endif;?>
                <br /><br />
                <?php echo $this->translate($this->escape((string) $config->description))?>
            <?php else:?>
                <?php echo $this->translate('No XML configuration file (configuration.xml)')?>
            <?php endif;?>
        </div>
    <?php endif;?>
<?php endforeach;?>