<?php echo $this->doctype(); ?>
<?php $locale = str_replace('_', '-', $this->locale)?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->locale?>" xml:lang="en">
	<head>
		<title><?php echo Tri_Config::get('tri_title')?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->appCharset?>"/>
        <base href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/" />
        <link rel="shortcut icon" href="favicon.ico" />
        <?php 
            $this->headLink()->prependStylesheet('css/'. Tri_Config::get('tri_theme_style').'.css')
                             ->prependStylesheet('css/style.css')
                             ->prependStylesheet('css/jquery-ui.css')
                             ->prependStylesheet('css/utils.css')
                             ->prependStylesheet('css/bootstrap.css');

            if ($locale != 'en') { 
                $this->headScript()->prependFile('js/jquery/ui/i18n/jquery.ui.datepicker-' . $locale . '.js')
                                   ->prependFile('js/ckeditor/lang/' . strtolower($locale) . '.js'); 
            }
            
            $this->headScript()->prependFile('js/jquery/jquery.strength.js')
                               ->prependFile('js/jquery/jquery-ui.min.js')
                               ->prependFile('js/jquery/jquery.maskedinput.js')
                               ->prependFile('js/jquery/jquery.other.js')
                               ->prependFile('js/ckeditor/ckeditor.js')
                               ->prependFile('js/jquery/jquery.min.js');
            
            echo $this->headMeta();
            echo $this->headLink();
            echo $this->headScript();
         ?>
         <style>
             <?php echo Tri_Config::get('tri_custom_css');?>
         </style>
	</head>
    <body>
        <script type="text/javascript">
            $.datepicker.setDefaults({showOn: "button",
                                      buttonImage: "img/calendar.gif",
                                      showOtherMonths: true,
                                      selectOtherMonths: true,
                                      buttonImageOnly: true});
        </script>
        
        <?php if (!$this->removePagePlugin): ?>
            <div class="pages">
                <ul>
                    <li><a href="index"><?php echo $this->translate('home')?></a></li>
                    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                        <li><a href="user/logout"><?php echo $this->translate('logout')?></a></li>
                    <?php endif;?>
                </ul>
            </div>
            <?php echo $this->widget('fix_header'); ?>
        <?php endif ?>
        <div id="loading"><?php echo $this->translate('Loading')?></div>
        <div class="row header">
            <div class="column">
                <h1>Trilhas</h1>
            </div>
        </div>
        <div class="container">
            <?php if ($this->messages):?>
                <div class="message">
                    <ul>
                        <?php foreach ($this->messages as $message): ?>
                            <li><?php echo $this->translate($message)?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif;?>
            <div class="box">
                <div class="header">
                    <h3><?php echo $this->translate($this->title)?></h3>
                </div>
                <div class="content">
                    <?php echo $this->layout()->content?>
                </div>
            </div>
            <div class="footer">
                <a href="http://www.preceptoread.com.br">
                    <img border="0" src="img/logo.png" alt="Logo Preceptor" />
                </a>
                <div class="info">
                    <?php echo Tri_Config::get('tri_title')?>
                </div>
            </div>
        </div>
        <?php echo $this->widget('fix_footer')?>

        <script type="text/javascript">
            $("#loading").bind("ajaxSend", function(){
                $(this).show();
            }).bind("ajaxComplete", function(){
                $(this).hide();
            });

            
        </script>
    </body>
</html>
