<div class="box">
    <div class="header">
        <h3><?php echo $this->translate('Courses'); ?></h3>
    </div>
    <div class="content courses">
        <?php if (count($this->data)) :?>
            <table class="datatable">
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Begin')?></th>
                    <th nowrap="nowrap"><?php echo $this->translate('Base text progress')?></th>
                </tr>
                <?php foreach ($this->data as $course): ?>
                    <tr>
                        <td>
                            <?php if (strtotime($course['begin']) < time() || Zend_Auth::getInstance()->getIdentity()->role != 'student'):?>
                                <a href="classroom/view/id/<?php echo $course['classroom_id'] ?>"><?php echo $course['name'] ?></a>
                            <?php else:?>
                                <?php echo $course['name'] ?>
                            <?php endif;?>
                            <span class="classroom-light">(<?php echo $course['classroom_name'] ?>)</span>
                        </td>
                        <td><?php echo $this->date($course['begin'])?></td>
                        <td nowrap="nowrap">
                            <?php $position  = Application_Model_Classroom::accessed($course['classroom_id'], Zend_Auth::getInstance()->getIdentity()->id)?>
                            <div class="access-bar">
                                <div class="progress" style="width: <?php echo $position?>px">&nbsp;</div>
                            </div>
                            (<?php echo $position?>%)
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php else: ?>
            <p><?php echo $this->translate('You are not registred in a classroom. See'); ?></p>
        <?php endif;?>
        <?php if (count($this->finalized)) :?>
            <h3><?php echo $this->translate('Finalized')?></h3>
            <table class="datatable">
                <?php foreach ($this->finalized as $finalized): ?>
                    <tr>
                        <td>
                            <?php echo $finalized['name'] ?>
                        </td>
                        <td>
                            <a href="panel/certificate/validate/uniqueId/<?php echo $finalized['unique_id']?>">
                                <img class="certificate" src="img/certificate.png" />
                                <?php echo $this->translate('Certificate')?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif;?>
    </div>
</div>