<?php if (count($this->data)) :?>
<table class="datatable">
    <tr>
    <h2><?php echo $this->translate('List of available courses'); ?></h2>
    </tr>
    <?php foreach ($this->data as $data): ?>
        <tr>
            <td><?php echo $data->cname?></td>
            <td><a href="classroom/sign/id/<?php echo $data->id ?>"><?php echo $this->translate('register')?></a></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php else: ?>
<p><?php echo $this->translate('You are not registred in a classroom. See'); ?></p>
<?php endif;?>