<div class="box courses">
    <div class="header">
        <h3><?php echo $this->translate('Courses');?></h3>
    </div>
    <div class="content">
        <?php if (count($this->data)):?>
            <?php foreach($this->data as $course): ?>
                <div class="item">
                    <img alt="<?php echo $course->name?>" src="upload/<?php echo $this->thumbnail($course->image, 'small')?>" width="40" height="40" />
                    <a href="course/view/id/<?php echo $course->id?>"><?php echo $course->name?></a>
                    <p><?php echo $course->description?></p>
                </div>
            <?php endforeach;?>
            <?php echo $this->paginationControl($this->data, null, null, $this->params); ?>
        <?php else: ?>
            <p><?php echo $this->translate('there are no records')?></p>
        <?php endif;?>
    </div>
</div>