<?php if (count($this->data)): ?>
    <table class="zebra-striped">
        <tr>
            <th><?php echo $this->translate('Name')?></th>
            <th></th>
        </tr>
        <?php foreach($this->data as $data): ?>
            <tr>
                <td><?php echo $data->name?></td>
                <td><a class="btn" href="migration/content/export/id/<?php echo $data->id?>"><?php echo $this->translate('Export')?></a> 
                    <a class="btn" href="migration/content/import/id/<?php echo $data->id?>"><?php echo $this->translate('Import')?></a></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->paginationControl($this->data, null, null, $this->params); ?>
<?php else:?>
    <p><?php echo $this->translate('No register')?></p>
<?php endif;?>