<p>Benvindo! Ficamos felizes em ter você por aqui.</p>
<p>Obrigado pela confiança nos cursos do TRILHAS ABERTAS.</p>
<p>Seus dados de cadastro são:</p>
<ul>
    <li><strong>Nome</strong>: <?php echo $this->data['name']?></li>
    <li><strong>E-mail</strong>: <?php echo $this->data['email']?></li>
    <li><strong>Senha</strong>: <?php echo $this->data['password']?></li>
</ul>
<p>Atenciosamente,<br />
Equipe Trilhas Abertas</p>