<div class="aright">
    <a class="btn primary" href="report/index/index"><?php echo $this->translate('Builder')?></a>
</div>
<?php if(count($this->data)):?>
    <table class="zebra-striped">
        <thead>
            <tr>
                <th><?php echo $this->translate('Nome');?></th>
                <th><?php echo $this->translate('Data de Criação');?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $key => $data):?>
                <tr class="<?php echo ($key%2)?'even':'odd';?>">
                    <td>
                        <a href="report/report/load/id/<?php echo $data->id; ?>">
                            <?php echo $data->name; ?>
                        </a>
                    </td>
                    <td><?php echo date('d/m/Y', strtotime($data->created)); ?></td>
                    <td class="aright">
                        <a class="btn" href="report/report/delete/id/<?php echo $data->id; ?>" class="delete"><?php echo $this->translate('Excluir')?></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->translate('there are no records')?></p>
<?php endif;?>
<script>
    $('.delete').click(function(){
        if(!confirm('<?php echo $this->translate('Deseja realmente excluir?');?>')){
            return false;
        }
    });
</script>