<?php if (file_exists(APPLICATION_PATH . '/configs/application.ini')): ?>
    <p><?php echo 'application.ini ja existente';?></p>
<?php else: ?>
    <h1><?php echo $this->translate('Requirements')?></h1>
    <table class="datatable">
        <tr>
            <th><?php echo $this->translate('Item')?></th>
            <th><?php echo $this->translate('Configuration')?></th>
        </tr>
        <tr>
            <td>PHP Version</td>
            <td><?php echo version_compare(phpversion(), '5.2.4')?></td>
        </tr>
        <tr>
            <td>Mysql extension</td>
            <td><?php echo extension_loaded('mysql') && extension_loaded('pdo_mysql')?></td>
        </tr>
        <tr>
            <td>GD extension</td>
            <td><?php echo extension_loaded('gd')?></td>
        </tr>
        <tr>
            <td>Apache mode_rewrite enabled</td>
            <td><?php echo in_array('mod_rewrite', apache_get_modules())?></td>
        </tr>
        <tr>
            <td>/application/configs is writable</td>
            <td><?php echo is_writable(APPLICATION_PATH . '/configs/')?></td>
        </tr>
        <tr>
            <td>/data is writable</td>
            <td><?php echo is_writable(APPLICATION_PATH . '/../data')?></td>
        </tr>
        <tr>
            <td>/plugins is writable</td>
            <td><?php echo is_writable(APPLICATION_PATH . '/../plugins')?></td>
        </tr>
        <tr>
            <td>/themes is writable</td>
            <td><?php echo is_writable(APPLICATION_PATH . '/../themes')?></td>
        </tr>

    </table>
    <br />
    <p class="aright"><a href='form.php' class='button'><?php echo $this->translate('Install')?></a></p>
<?php endif; ?>
