<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
        <title>Trilhas</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="shortcut icon" href="favicon.ico" />
        <link href="../css/grid.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/utils.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/style.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="../js/jquery/jquery.min.js"></script>
	</head>
    <body>
        <div class="pages">
            <ul>
                <li><a href="index">Home</a></li>
            </ul>
        </div>
        <div class="row header">
            <div class="column">
                <h1>Trilhas</h1>
            </div>
        </div>
        <div class="main">
            <div class="row">
                <div class="column grid_16">
                    <?php if ($this->layout()->messages):?>
                        <div class="message">
                            <ul>
                                <?php foreach ($this->layout()->messages as $message): ?>
                                    <li><?php echo $this->translate($message)?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <br />
                    <?php endif;?>
                    <div class="box">
                        <div class="header"><?php echo $this->translate('Installation')?></div>
                        <div class="content">
                            <?php echo $this->layout()->content?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="column grid_16">
                <div class="footer">
                    <a href="http://www.preceptoread.com.br">
                        <img border="0" src="../img/logo.png" alt="Logo Preceptor" />
                    </a>
                    <div class="info">&nbsp;</div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('input[type=button], input[type=submit]').button();
        </script>
    </body>
</html>
