<div class="row" style="margin-left: 60px;">
    <div class="column grid_6">
        <h2><?php echo $this->translate('Already have an account?');?></h2>
        <p><?php echo $this->translate('Login here using your email and password.')?></p>
        <br />
        <?php echo $this->form?>
        <br />
        <a href="forgot/index"><?php echo $this->translate('Forgot password') ?></a>
    </div>
    <?php if (Tri_Config::get('tri_new_user_to_guest')) :?>
        <div class="column grid_6" style="border-left: 1px dotted #ddd; padding-left: 75px;">
            <h2><?php echo $this->translate('Is this your first time here?');?></h2>
            <p><?php echo $this->translate('Create your new user. It is quick and easy.')?></p>
            <br />
            <?php 
                $form = new Application_Form_User();
                $form->removeElement('description');
                $form->removeElement('born');
                $form->removeElement('sex');
                $form->removeElement('image');
                echo $form;
            ?>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    if ($('#fixed').length) {
        window.location('index');
    }
    $("#passwordIn").strength();
</script>
