<div class="row">
    <div class="column grid_5">
        <?php echo $this->form?>
        <?php echo $this->captcha?>
    </div>
    <?php if (Tri_Config::get('tri_new_user_to_guest')) :?>
        <div class="column grid_5" style="border-left: 1px dotted #ddd; padding-left: 20px;">
            <h2><?php echo $this->translate('new');?> <?php echo $this->translate('user');?></h2>
            <?php 
                $form = new Application_Form_User();
                $form->removeElement('description');
                $form->removeElement('born');
                $form->removeElement('sex');
                $form->removeElement('image');
                echo $form;
            ?>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
    if ($('#fixed').length) {
        window.location('index');
    }
</script>
