<div class="box">
    <div class="main index">
        <div class="header">
            <h3><?php echo $this->course;?> - <?php echo $this->translate('base-text'); ?></h3>
        </div>
        <div id="content" class="content">
            <div class="nav">
                <div class="bread">
                    <span></span>
                </div>
                <div class="buttons">
                    <div class="treeview">
                        <img class="button" src="img/treeview.gif" />
                        <div></div>
                    </div>
                    <div class="prevnext">
                        <a class="previous" href="content/previous"><?php echo $this->translate('previous content') ?></a>&nbsp;
                        <a class="next" href="content/next"><?php echo $this->translate('next content') ?></a>
                    </div>
                    <div class="clear-min">&nbsp;</div>
                </div>
            </div>
            <div id="content-main-content" class="text">

            </div>
            <div class="nav">
                <div class="buttons">
                    <div class="prevnext">
                        <a class="previous" href="content/previous"><?php echo $this->translate('previous content') ?></a>&nbsp;
                        <a class="next" href="content/next"><?php echo $this->translate('next content') ?></a>
                    </div>
                    <div class="clear-min">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="static/content/public/js/navigation.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#content').navigation('<?php echo str_replace("\'", "'", $this->data)?>', {current: <?php echo $this->current?>});
    });
</script>