<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
        <title>Trilhas</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <base href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/" />
        <link rel="shortcut icon" href="../favicon.ico" />
        <link href="../css/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/utils.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/style.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="../js/jquery/jquery.min.js"></script>
	</head>
    <body>
        <div class="pages">
            <ul>
                <li><a href="index"><?php echo $this->translate('Installation')?></a></li>
            </ul>
        </div>
        <div class="row header">
            <div class="columns">
                <h1>Trilhas</h1>
            </div>
        </div>
        <div class="container">
            <div class="box">
                <div class="header">
                    <h3><?php echo $this->translate('Installation')?></h3>
                </div>
                <div class="content">
                    <?php if ($this->messages):?>
                        <div class="message">
                            <ul>
                                <?php foreach ($this->messages as $message): ?>
                                    <li><?php echo $this->translate($message)?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <br />
                    <?php endif;?>
                    <?php echo $this->layout()->content?>
                </div>
            </div>
            <div class="footer">
                <a href="http://www.preceptoread.com.br">
                    <img border="0" src="../img/logo.png" alt="Logo Preceptor" />
                </a>
                <div class="info">&nbsp;</div>
            </div>
        </div>
    </body>
</html>